name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - release

permissions:
  contents: write
  id-token: write

jobs:
  publish-tauri:
    permissions:
      contents: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ''

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      # Step to zip the specific .exe file
      - name: Zip the executable
        run: |
          mkdir -p release
          zip release/Zwei.zip target/release/Zwei.exe

      # Step to upload the zip file to the release
      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.tauri.outputs.upload_url }}
          asset_path: release/Zwei.zip
          asset_name: Zwei.zip
          asset_content_type: application/zip